### ISSUE TITLE
How to play music when kill app

### ISSUE THREAD

**Issue by binbin269x** [brianwernick/PlaylistCore#42] opened 2017-05-23 02:18 UTC
When i kill app, service kill. i want kill app then service play music continue play.
i setup
        setupForeground();
 and 
    public int getServiceContinuationMethod() {
        return START_STICKY;
    }

but not working.
plz help me

**Comment by brianwernick** [comment] 2017-06-03 23:05
Sorry for the late reply; I thought that this used to work but no longer so I'll add it to my list of things to fix and verify for the upcoming 2.0 release.

**Comment by brianwernick** [comment] 2017-07-04 20:37
So the root cause of this is the call to `onDestroy()` from `onTaskRemoved` (see [PlaylistServiceCore#onTaskRemoved(Intent)](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L330)). So as a fix for the current library (1.x) you can override that method and perform a no-op (this is the default of services)

**Comment by brianwernick** [comment] 2017-07-23 15:21
Fixed on the 2.0 branch so I'm going to close this

**Closed as completed by brianwernick** 2017-07-23 15:21 UTC
Labels: Bug
