### ISSUE TITLE
How to hide play button while preparing song in notification bar 

### ISSUE THREAD

**Issue by pratheepchowdhary** [brianwernick/PlaylistCore#35] opened 2017-02-03 17:16 UTC
Hello sir how to hide notification play button while music preparing this causes me to skip to next song when clicks on play button while preparing the song at first
and thank u sir for such good library

**Comment by brianwernick** [comment] 2017-02-03 20:34
Duplicate of #15

**Closed as completed by brianwernick** 2017-02-03 20:34 UTC
Labels: Duplicate
