### ISSUE TITLE
Starting Youtube triggers unexpected behavior when ExoMedia is playing in the background

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/PlaylistCore#7] opened 2016-03-29 20:39 UTC
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- PlaylistCore version: `1.0.1`
- Device OS version: `6.0`
- Devide Manufacturer: `LG`
- Device Name: `Nexus 5`
###### Reproduction Steps
1.  start the audio playback and put it into background.
2. start the youtube app and play a video.
3. the playback of ExoMedia has stopped. But the playback state in the notification bar still show a pause button.
4. press the play/pause button two times, the audio will resume.  And if you go to Youtube to play the video, you will hear both the audio from ExoMedia and Youtube.
###### Expected Result

for step 3, it should show a start button as the playback is stopped by Youtube.
for step 4, there should be only one audio being played. Either Youtube or ExoMedia.

**Comment by brianwernick** [comment] 2016-03-30 20:03
There are two parts to this then:
1. The Notification state doesn't update correctly when audio focus is lost (e.g. YouTube starts playback)
2. Either ExoMedia isn't correctly re-acquiring audio focus, or YouTube isn't correctly abiding by the audio focus (We'll have to look more in to this part)

**Comment by brianwernick** [comment] 2016-04-09 16:17
I'm unable to reproduce the first part as listed above.  Every time YouTube starts playback, the notification updates to display the play icon instead of the pause icon.

**Comment by brianwernick** [comment] 2016-04-09 23:21
The second part has been fixed in https://github.com/brianwernick/PlaylistCore/pull/10

**Closed as completed by brianwernick** 2016-04-09 23:21 UTC
Labels: Bug
